name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight (UTC)
  workflow_dispatch:       # Allows you to manually trigger it
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: Ved-nt
          outputs: dist/snake.svg

      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
